### ISSUE TITLE
New Maintainer

### ISSUE THREAD

**Issue by ProjectEther** [Sideflipsa-ga/sideflipsaga#33]
Me and @MrBrain295 are leaving @Sideflipsa-ga we are needing a new maintainer. Apply by emailing. <a href="mailto:sideflipsaga-devs@googlegroups.com">sideflipsaga-devs@googlegroups.com</a>.

**Comment by SubjectEther** [comment]
@mrdoob lol

**Comment by MrBrain295** [comment]
Never mind this has changed.
